### ISSUE TITLE
LOGO and phone icon goes over the content - Mobile

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Perfection-Site#11]
LOGO and phone icon goes over the content in the mobile version while scrolling down.
Apply to only Chrome browser.
 Other browsers it looks fine. 
![image](https://user-images.githubusercontent.com/26923359/32171551-3389b57e-bd81-11e7-9233-7fdb29aa131f.png)

**Comment by MeanEYE** [comment]
Cleared cache an everything?

**Comment by talovdat** [comment]
Chrome browser App crushed in my mobile. Reinstalled and the issue was gone.
Closing issue.
