### ISSUE TITLE
Embed video between footer and features section.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Perfection-Site#8]
![image](https://user-images.githubusercontent.com/1911594/32055571-7d74a13e-ba62-11e7-8fdf-ab6ff50e12ff.png)
The following [video](https://www.youtube.com/watch?v=r-UX1mFT3RQ) needs to be embedded between these sections in separate white background section. More details to follow from @talovdat.

**Comment by talovdat** [comment]
Title of video should be: אבי זלוטוב מחפש ומוצא פתרון 

English: Avi Zlotov search and find a solution, in case you were wondering...
